pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {

        stage('Build Maven') {
            steps {
                dir('spring-cloud-gateway') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('spring-cloud-gateway') {
                    sh 'ls -la'
                    sh 'docker-compose build'
                }
            }
        }

        stage('Run Containers') {
            steps {
                dir('spring-cloud-gateway') {
                    sh 'docker-compose up -d'
                }
            }
        }

        stage('Verify Containers') {
            steps {
                dir('spring-cloud-gateway') {
                    sh 'docker ps'
                }
            }
        }
    }
}