spring.application.name=gateway

server.port=8080

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka

logging.level.root=WARN
logging.level.org.springframework=INFO

spring.cloud.gateway.routes[0].id=car-service
spring.cloud.gateway.routes[0].uri=http://car-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/cars/**